# -*- coding: utf-8 -*-
"""ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tktQs2vTZf-P5l8BOlmLRvKtmLhq4dX
"""

#Weather modelling using the Quadratic Equation
a = float(input("Enter the a value: "))
b = float(input("Enter the b value: "))
c = float(input("Enter the c value: "))
x = float(input("Enter the x value: "))
y = a * x * x + b * x + c
print("For the values of ",a, " ",b, " ", " ", c, " Y is: ",y)